#端口
server:
  port: 8150

#应用信息
spring:
  application:
    name: mhq0123-assistant-edgeservice-message

  #默认开发
  profiles:
    active: dev

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8177/eureka/

#设置断路器的超时（默认1s）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-InMilliseconds: 5000

#开发
---
spring:
  profiles: dev

#日志
logging:
  config: classpath:logback-dev.xml



---
#生产
spring:
  profiles: prod

logging:
  config: classpath:logback-prod.xml